---
- hosts: udv
  become: yes
  gather_facts: true

  tasks:
  - name: Add repo key docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add repo docker
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable 
      state: present

  - name: Install Docker
    apt:
      pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose
      update_cache: yes
      state: present

  - name: Clone a repo
    git:
      repo: https://github.com/BaTpyLLI/udv.git
      dest: /tmp/Git

  - name: Build nginx + php-fpm on alpine in one image
    community.docker.docker_image: 
      name: nginx-php-fpm
      build:
        path: /tmp/Git/Docker/alpine
      source: build
    tags: nginx-php-fpm

  - name: Start container nginx + php-fpm
    community.docker.docker_container:
      name: web-site
      image: nginx-php-fpm
      state: started
      ports:
       - "1000:80"
    tags: nginx-php-fpm

  - name: Run `docker-compose up` 
    community.docker.docker_compose:
      project_src: /tmp/Git/Docker/compose
      build: no
      state: present
    tags: compose

  - name: Build nginx on alpine
    community.docker.docker_image:
      name: nginx-alpine
      build:
        path: /tmp/Git/Docker/alpinev2/nginx
      source: build
    tags: nginx-php-alpine

  - name: Build php-fpm on alpine
    community.docker.docker_image:
      name: php-fpm-alpine
      build:
        path: /tmp/Git/Docker/alpinev2/php-fpm
      source: build
    tags: nginx-php-alpine

  - name: Start nginx 
    community.docker.docker_container:
      name: nginx
      images: nginx-alpine
      networks:
        - name: nginx-php-fpm
      state: started
      ports:
       - "2000:80"
    tags: nginx-php-alpine

  - name: Start nginx
    community.docker.docker_container:
      name: php-fpm
      images: php-fpm-alpine
      networks:
        - name: nginx-php-fpm
      state: started
    tags: nginx-php-alpine

  - name: Remove tmp directory whith Git
    ansible.builtin.file:
      path: /tmp/Git
      state: absent

